# Copyright (c) 2026 Salvo Giangreco
# SPDX-License-Identifier: GPL-3.0-or-later

# Platform configuration file for Samsung Exynos 9810 devices (exynos9810)
# The actually-verified, known-booting/known-working camera baseline is kept
# in the repository's embedded Exynos9810 payloads. External donor paths are
# optional development overlays only; clean builds do not require them.
# Note10 Lite's own N770F vendor blobs are a different, unverified camera HAL
# binary and are never selected by default.
TARGET_BOARD_API_LEVEL="${EXYNOS9810_TARGET_BOARD_API_LEVEL:-33}"
# Keep instrumentation opt-in for production images. The late logger can be
# enabled explicitly while reproducing a boot failure.
EXYNOS9810_ENABLE_SYSTEM_BOOT_DEBUG="${EXYNOS9810_ENABLE_SYSTEM_BOOT_DEBUG:-false}"
EXYNOS9810_ENABLE_VENDOR_BOOT_TRACE="${EXYNOS9810_ENABLE_VENDOR_BOOT_TRACE:-false}"

# Partitions
# Expands the Exynos9810 repartition baseline for One UI 8:
# system=9500MiB, vendor=1300MiB, odm=700MiB, cache=600MiB.
TARGET_BOOT_PARTITION_SIZE=57671680
TARGET_DTBO_PARTITION_SIZE=8388608
TARGET_CACHE_PARTITION_SIZE=629145600
TARGET_SYSTEM_PARTITION_SIZE=9961472000
TARGET_VENDOR_PARTITION_SIZE=1363148800
TARGET_ODM_PARTITION_SIZE=734003200

# Dynamic partitions
TARGET_USE_DYNAMIC_PARTITIONS=false

# OS
TARGET_OS_SINGLE_SYSTEM_IMAGE="essi"
# Production builds stay EROFS. Test builds may opt into ext4 with
# EXYNOS9810_TARGET_OS_FILE_SYSTEM_TYPE=ext4 so live recovery/debug patches
# can be applied without changing the production default.
TARGET_OS_FILE_SYSTEM_TYPE="${EXYNOS9810_TARGET_OS_FILE_SYSTEM_TYPE:-erofs}"
TARGET_OS_BUILD_PRODUCT_PARTITION=false
TARGET_OS_BUILD_SYSTEM_EXT_PARTITION=false
TARGET_DISABLE_AVB_SIGNING=true

# SEC Product Feature
TARGET_AUDIO_CONFIG_RECORDALIVE_LIB_VERSION="none"
TARGET_AUDIO_SUPPORT_ACH_RINGTONE=false
TARGET_AUDIO_SUPPORT_DUAL_SPEAKER=true
TARGET_AUDIO_SUPPORT_VIRTUAL_VIBRATION=false
TARGET_CAMERA_SUPPORT_CAMERAX_EXTENSION=false
TARGET_CAMERA_SUPPORT_CUTOUT_PROTECTION=false
TARGET_CAMERA_SUPPORT_MASS_APP_FLAVOR=true
TARGET_CAMERA_SUPPORT_SDK_SERVICE=false
TARGET_COMMON_CONFIG_MDNIE_MODE="65303"
TARGET_COMMON_SUPPORT_DYN_RESOLUTION_CONTROL=true
TARGET_COMMON_SUPPORT_EMBEDDED_SIM=false
TARGET_COMMON_SUPPORT_HDR_EFFECT=true
TARGET_DVFSAPP_CONFIG_DVFS_POLICY_FILENAME="dvfs_policy_default"
TARGET_FINGERPRINT_CONFIG_SENSOR="google_touch_rear,settings=3,navi=1"
TARGET_LCD_CONFIG_COLOR_WEAKNESS_SOLUTION="3"
TARGET_LCD_CONFIG_CONTROL_AUTO_BRIGHTNESS="3"
TARGET_LCD_CONFIG_HFR_DEFAULT_REFRESH_RATE="60"
TARGET_LCD_CONFIG_HFR_MODE="0"
TARGET_LCD_SUPPORT_MDNIE_HW=true
TARGET_RIL_FEATURES="onebinary"
TARGET_RIL_SIM_CONFIG_MULTISIM_TRAYCOUNT="1"
TARGET_RIL_SUPPORT_WATERPROOF_SIM_TRAY_MSG=true
TARGET_WLAN_CONFIG_CONNECTION_PERSONALIZATION="0"
TARGET_WLAN_CONFIG_CPU_CSTATE_DISABLE_THRESHOLD="0"
TARGET_WLAN_CONFIG_DATA_ACTIVITY_AFFINITY_BOOSTER_THRESHOLD="0"
TARGET_WLAN_CONFIG_DYNAMIC_SWITCH="0"
TARGET_WLAN_CONFIG_L1SS_DISABLE_THRESHOLD="0"
TARGET_WLAN_SUPPORT_80211AX=false
TARGET_WLAN_SUPPORT_80211AX_6GHZ=false
TARGET_WLAN_SUPPORT_APE_SERVICE=false
TARGET_WLAN_SUPPORT_LOWLATENCY=false
TARGET_WLAN_SUPPORT_MBO=true
TARGET_WLAN_SUPPORT_MOBILEAP_5G_BASEDON_COUNTRY=true
TARGET_WLAN_SUPPORT_MOBILEAP_6G=false
TARGET_WLAN_SUPPORT_MOBILEAP_DUALAP=false
TARGET_WLAN_SUPPORT_MOBILEAP_OWE=false
TARGET_WLAN_SUPPORT_MOBILEAP_POWER_SAVEMODE=false
TARGET_WLAN_SUPPORT_MOBILEAP_PRIORITIZE_TRAFFIC=false
TARGET_WLAN_SUPPORT_MOBILEAP_WIFI_CONCURRENCY=true
TARGET_WLAN_SUPPORT_MOBILEAP_WIFISHARING_LITE=true
TARGET_WLAN_SUPPORT_SWITCH_FOR_INDIVIDUAL_APPS=true
TARGET_WLAN_SUPPORT_TWT_CONTROL=false
TARGET_WLAN_SUPPORT_WIFI_TO_CELLULAR=false
